[tool.poetry]
name = "django-project-store"
version = "0.1.0"
description = "Django project store"
authors = ["webmiko <webmiko@icloud.com>"]
readme = "README.md"
packages = [{include = "django_project_store"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "6.0.1"
psycopg2-binary = "^2.9"
python-dotenv = "^1.0"

[tool.poetry.group.dev.dependencies]
black = "^24.0"
flake8 = "^7.0"
pylint = "^3.0"
mypy = "^1.8"
isort = "^5.13"
pytest = "^8.0"
pytest-django = "^4.8"
django-debug-toolbar = "^4.3"
ipython = "^8.20"

[tool.black]
line-length = 100
target-version = ['py310', 'py311', 'py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.pylint.messages_control]
max-line-length = 100

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
